apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.nameOverride }}-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  ApiKey: {{ .Values.apiKey | quote }}
  ConnectionStrings__BlogDb: "Host={{ .Values.db.host }};Port={{ .Values.db.port }};Database={{ .Values.db.name }};Username={{ .Values.db.username }};Password={{ .Values.db.password }}"
