kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.nameOverride }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.nameOverride }}
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: {{ .Values.nameOverride }}
    deploymentconfig: {{ .Values.nameOverride }}
