apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.nameOverride }}-credentials
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.credentials.database }}
  POSTGRES_USER: {{ .Values.credentials.username }}
  POSTGRES_PASSWORD: {{ .Values.credentials.password | quote }}
  POSTGRESQL_DATABASE: {{ .Values.credentials.database }}
  POSTGRESQL_USER: {{ .Values.credentials.username }}
  POSTGRESQL_PASSWORD: {{ .Values.credentials.password | quote }}
