library identifier: "pipeline-library@master", retriever: modernSCM(
  [$class: "GitSCMSource",
   remote: "https://github.com/redhat-cop/pipeline-library.git"])

pipeline{
    agent{
        label "nodejs"
    }
    stages{
        stage("Checkout code"){
            steps{
                git 'https://github.com/shift-left-security-poc/openshift-demo-pipeline.git'
            }
        }
        stage("Aikido security scan"){
            steps{
                withCredentials([string(credentialsId: 'aikido-ci-api-key', variable: 'AIKIDO_API_KEY')]) {
                    sh '''
                    COMMIT_SHA=$(git rev-parse HEAD)
                    npx -y @aikidosec/ci-api-client scan-release openshift-demo-pipeline "$COMMIT_SHA" --apikey "$AIKIDO_API_KEY"
                    '''
                }
            }
        }
        stage("Build code"){
            steps{
                sh '''
                cd gremlins
                npm install
                npm run-script build
                '''
            }
        }
        stage("Binary build"){
            steps{
                binaryBuild([
                        buildConfigName: "gremlins-build",
                        buildFromFlag  : "--from-dir",
                        buildFromPath  : "${WORKSPACE}/gremlins/build/"
                ])
            }
        }
    }
}
